names_reg = [
	"Tetfleetrad", 
	"New Sop", 
	"Triateirthlstead", 
	"North Graysbeytgrave", 
	"South Xbridgeubeach", 
	"Bridhyhamhol", 
	"Weythornlong", 
	"Streewel Castle", 
	"East Manmichi", 
	"Colhetstone", 
	"New Chetvennchin", 
	"Leighmitworth", 
	"Nextsel", 
	"Nypoy With Kentwhist", 
	"New Queenfilleek", 
	"Royal Xstoweedge", 
	"Sturandhead", 
	"West Fuhing", 
	"Newgrasfield", 
	"Wootrith", 
	"Bridthythames", 
	"Stonequethiel", 
	"Ofvil", 
	"Royal Bascalne", 
	"St Swanco", 
	"New Ting", 
	"Granswade Upon Chardglos", 
	"Kempshanstanley", 
	"East Ayforth", 
	"Bridsouthkings", 
	"East Tawwlandfram", 
	"Royal Osdiss Under Tenmol", 
	"Lynecraypool", 
	"Braunsmere-By-The-Sea", 
	"Luthythelymedon", 
	"Wyecoe Under Stainescay", 
	"West Princesdrew", 
	"Stonewenchead", 
	"Calmawes", 
	"North Dgwarewil", 
	"South Rawtrawot", 
	"Stonemaingar", 
	"Earmid-On-River", 
	"South Thillayl", 
	"Eastsaints", 
	"Miltrentnche", 
	"Tilwent Upon Chipwston", 
	"Fordlittstone", 
	"Rsleyhurst", 
	"South Shingbrad", 
	"North Nagebig", 
	"Stonedronlumb Under Xestreet", 
	"Bathnchelgate", 
	"New Mel", 
	"Beaba", 
	"New Kidsrashields", 
	"Msleynoakscombe", 
	"Winport Under Ego", 
	"North Nacra", 
	"Northchwood-In-Wardshampwich", 
	"Hithecoldpres", 
	"Stoneveyrnardlooe", 
	"Spro", 
	"Gravega", 
	"Hohampton", 
	"Yeoalclea", 
	"Hebbrix", 
	"New Ntagekin", 
	"Cavebroside", 
	"South Merescot", 
	"Thbulet", 
	"Bridlimarshchor", 
	"Xmundtashmingchester", 
	"New Bed", 
	"Azinport", 
	"Lothngaybridge", 
	"Sysportcombe", 
	"Watlowston-On-River", 
	"West Chworthstal Upon Zouchpe", 
	"Stonenelwhi", 
	"Wallompshot", 
	"East Nesshepwed", 
	"Bridstokeskelearl", 
	"Frizion-In-Ntecrook", 
	"Loden", 
	"West Becclesbru", 
	"North Ryeroyal", 
	"North Pdentad", 
	"East Bawbid", 
	"Royal Lksham", 
	"Justwlishmouth", 
	"St Shdendun", 
	"West Unpoint", 
	"Stoneponshall Upon Skernbrough", 
	"East Hayhex", 
	"New Modec With Spenpham", 
	"Hartcorchinington", 
	"Loungates", 
	"South Needling", 
]

arrival_verbs =[
	"arrive to a new place",
	"stop by this place",
	"decide to make a camp at this site",
	"take a small break here",
	"decide to stop here",
	]
	
scenery_generic =[
	"The scenery is monotonous",
	"The surroundings are the same as before",
	"This place you are at is like many others you have been to",
	"Nothing interesting around here",
	"You keep walking",
	"Time goes on, as you make your way, step by step",
	"There is nothing interesting in particular around here",
	"There is nothing worth exploring here",
	"It is not worth staying around",
	"You keep walking as the surroundings are the same around you",
	"Nothing interesting about this place you have passed by",
	"Not a single soul around",
	"The places you see seem to be too... random",
	]
	
features_generic =[
	"The path ahead is rocky and hard to traverse",
	"The road ahead takes you uphill",
	"It is particularly easy to go by this path since it goes downhill",
	"There are a lot of exposed sharp rocks around",
	"You can see a spot with withered trees and lack of any other vegetation",
	"The path takes you through the field of wild flowers",
	]

walk_verb = [
	"keep moving on",
	"resume your travel",
	"go on",
	"depart",
	"go away",
	]
	
action_done = [
	"looking aroung",
	"examining the thing",
	"checking the things aroung",
	"exploring here",
	"scratching your head and pondering why is it here",
	]
	
action_verb_ing = [
	"having a short rest",
	"revising your possessions",
	"taking a short break and helping yourself to some food",
	"scavenging for some food and water",
	"briefly studying the surroundings",
	"pondering what to do next",
	]

explore_verb = [
	"You explore",
	"You look around",
	"You examine",
	"You decide to not to explore",
	"You curb your curiosity, avoid approaching",
	"You are exploring",
	"You are looking around",
	"You are examining",
	"You are deciding to not to explore",
	"You are curbing your curiosity, avoid approaching",
	"You are deciding to explore",
	"You are deciding to look around",
	"You are deciding to examine",
	"You are deciding to not to explore",
	"You are deciding to curb your curiosity, avoid approaching",
	"You take a look",
	"You are looking around",
	"You are deciding to look around",
	"You are deciding against looking around",
	"You loiter around",
	"You are taking a refreshing break near the",
	"You check",
	"You are checking",
	"You decide to check",
	"You decide against checking",
	]

spot_verb = [
	"spot",
	"see",
	"notice",
	"can see",
	]
	
after_word = [
	"and after that",
	"and after finishing",
	"and once done",
	"and once you finish",
	]

prox_word = [
	"here",
	"where you are",
	"around here",
	"at this place",
	"around you",
	"at this site",
	"there",
	]
	

terrain_type = [
	"rocky",
	"muddy",
	"sandy",
	"dusty",
	"covered in gravel",
	"cracked",
	"moist",
	]
	
terrain_word = [
	"ground",
	"terrain",
	"soil",
	"land",
	]
	
vegetation_word = [
	"lush",
	"sparse",
	"dense",
	"green",
	"yellow",
	"absent",
	]
	
vegetation_type = [
	"trees",
	"shrubs",
	"grasses",
	"trees and shrubs",
	"shrubs and grasses",
	]
	
constructions_word = [
	"an old",
	"an abandoned",
	"a decently looking",
	"a spooky",
	"a haunted",
	"a suspiciously looking",
	"a destroyed",
	"a",
	]
	
constructions_type = [
	"village",
	"house",
	"hut",
	"wall remains",
	"castle remains",
	"well",
	"shrine",
	"tower",
	]
	
natural_features_type = [
	"a stream",
	"a cave",
	"a faint path in woods",
	]
	
types_reg = [
	"Area", 
	"Barony", 
	"County", 
	"Country", 
	"Constituency", 
	"Division", 
	"Duchy", 
	"Governorate", 
	"Kingdom", 
	"Local council", 
	"Municipality", 
	"Rural Municipality", 
	"Regional Municipality", 
	"Regional county", 
	"Parish", 
	"Oblast", 
	"Prefecture", 
	"Principality", 
	"Province", 
	"Region", 
	"Republic", 
	"Riding", 
	"State", 
	"Special administrative region", 
	"Territory", 
	"Voivodeship",
	]
